### ISSUE TITLE
Categorize expenses for better organization

### ISSUE THREAD

**Issue by seanlim** [AY2425S1-CS2103-F13-1/tp#28] opened 2024-09-11 09:42 UTC
As a user managing expenses across various categories, I want to categorize my expenses (e.g., "Rent," "Groceries," "Utilities"), so that I can organize and understand my spending habits better.

**Comment by SeeYangZhi** [comment] 2024-09-13 04:52
Duplicate of #3

**Closed by SeeYangZhi** 2024-09-13 04:52 UTC
Labels: type.Story
