### ISSUE TITLE
Add shared expenses

### ISSUE THREAD

**Issue by seanlim** [AY2425S1-CS2103-F13-1/tp#23] opened 2024-09-11 09:01 UTC
As a tech-savvy student, I want to create a new shared expense group for my roommates, so that I can easily manage and track our collective expenses.

**Comment by SeeYangZhi** [comment] 2024-09-13 04:41
@seanlim This is a duplicate of #1, I will close this.

**Closed by SeeYangZhi** 2024-09-13 04:41 UTC
