### ISSUE TITLE
[PE-D][Tester C] Contacts with different name capitalization are not seen as duplicate

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#385] opened 2024-11-08 17:35 UTC
It is unlikely that 'Alice' and 'alice' refers to a different person. Especially when their other contact details are the same

![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/e14ce816-1cfc-4947-8cbb-8a8751b9c3b1.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hazzle23/ped#4

**Comment by Dino-Nuggies** [comment] 2024-11-09 02:20
Thank you for catching this feature flaw. Will be fixed for 1.6 release.

**Comment by Dino-Nuggies** [comment] 2024-11-09 02:37
This issue will be closed, look for #456

**Comment by SeeYangZhi** [comment] 2024-11-10 03:51
**Case Sensitivity in Names May Result in Perceived Duplicates in Address Book**: Currently, SpleetWaise treats names as case-sensitive, meaning that variations like “bob”, “bOb”, “boB”, “Bob”, “BOB”, and “BoB” are considered distinct entries (even when all Bobs have the same phone number). This may lead to perceived duplicate entries if consistent capitalisation is not used. For example, “Alex Yeoh” and “alex yeoh” would be stored as separate contacts, even if both entries have the same phone number. The intended behavior in future releases is for case-insensitive handling, where entries like “Alex Yeoh” and “alex yeoh” with the same phone number would be considered potential duplicates and a warning or alert could be displayed to the user. Until this update, users are advised to maintain consistent capitalisation when adding contacts to avoid unintentional duplicates.

**Comment by SeeYangZhi** [comment] 2024-11-10 03:52
> Thank you for catching this feature flaw. Will be fixed for 1.6 release.

This FeatureFlaw will not be fixed in 1.6 due to feature freeze, UG/DG will be updated accordingly.

**Closed by SeeYangZhi** 2024-11-10 03:52 UTC
Labels: severity.Low, type.FutureEnhancement
