### ISSUE TITLE
Product flaw: filter transaction by categories in UI

### ISSUE THREAD

**Issue by Dino-Nuggies** [AY2425S1-CS2103-F13-1/tp#351] opened 2024-11-07 09:07 UTC

**Comment by rollingpencil** [comment] 2024-11-07 09:25
Duplicate of #204

**Comment by rollingpencil** [comment] 2024-11-07 09:26
Duplicate of https://github.com/AY2425S1-CS2103-F13-1/tp/issues/204

**Closed by rollingpencil** 2024-11-07 09:25 UTC
Labels: priority.Medium
